# This file was generated by kuka_calib
# Transform from the world frame to the camera link
# Position
export base_cam_x_pos=0.847632
export base_cam_y_pos=0.0841824
export base_cam_z_pos=1.12201
#Rotation
export base_cam_x_rot=-0.467711
export base_cam_y_rot=-0.0556057
export base_cam_z_rot=0.880771
export base_cam_w_rot=-0.0489472
