# This file was generated by kuka_calib
# Transform from the base camera frame to the camera link
# Position
export cam_3_x_pos=0.631
export cam_3_y_pos=-0.376
export cam_3_z_pos=-0.088
#Rotation
export cam_3_x_rot=-0.316
export cam_3_y_rot=-0.094
export cam_3_z_rot=0.311
export cam_3_w_rot=0.891
