# This file was generated by kuka_calib
# Transform from the base camera frame to the camera link
# Position
export cam_3_x_pos=0.710014
export cam_3_y_pos=-0.322278
export cam_3_z_pos=-0.172142
#Rotation
export cam_3_x_rot=-0.318389
export cam_3_y_rot=-0.037722
export cam_3_z_rot=0.361644
export cam_3_w_rot=0.875453
