# This file was generated by kuka_calib
# Transform from the world frame to the camera link
# Position
export cam_4_x_pos=0.399149
export cam_4_y_pos=0.956105
export cam_4_z_pos=0.150103
#Rotation
export cam_4_x_rot=0.096831
export cam_4_y_rot=-0.048099
export cam_4_z_rot=-0.377945
export cam_4_w_rot=0.919493
