# This file was generated by kuka_calib
# Transform from the world frame to the camera link
# Position
export cam_5_x_pos=0.841712
export cam_5_y_pos=1.312272
export cam_5_z_pos=0.884292
#Rotation
export cam_5_x_rot=0.441485
export cam_5_y_rot=-0.012698
export cam_5_z_rot=-0.624241
export cam_5_w_rot=0.644401
