# This file was generated by kuka_calib
# Transform from the world frame to the camera link
# Position
export cam_2_x_pos=0.439353
export cam_2_y_pos=-0.865108
export cam_2_z_pos=0.225670
#Rotation
export cam_2_x_rot=-0.128168
export cam_2_y_rot=0.042191
export cam_2_z_rot=0.374533
export cam_2_w_rot=0.917343
