# This file was generated by kuka_calib
# Transform from the world frame to the camera link
# Position
# NOTE - THIS FILE IS NOT CURRENTLY USED - THIS TRANSFORM IS NOW IN THE ROBOT URDF
export cam_structure_x_pos=0.04
export cam_structure_y_pos=-0.08
export cam_structure_z_pos=0.03
#Rotation
export cam_structure_x_rot=0.000000
export cam_structure_y_rot=-0.000000
export cam_structure_z_rot=-0.7071
export cam_structure_w_rot=0.7071
