# This file was generated by kuka_calib
# Transform from the world frame to the camera link
# Position
export cam_1_x_pos=0.817487
export cam_1_y_pos=-1.175450
export cam_1_z_pos=0.889069
#Rotation
export cam_1_x_rot=-0.479410
export cam_1_y_rot=-0.006100
export cam_1_z_rot=0.508861
export cam_1_w_rot=0.714975
