# This file was generated by kuka_calib
# Transform from the world frame to the camera link
# Position
export cam_3_x_pos=0.000000
export cam_3_y_pos=-0.000000
export cam_3_z_pos=0.000000
#Rotation
export cam_3_x_rot=-0.000000
export cam_3_y_rot=-0.000000
export cam_3_z_rot=0.000000
export cam_3_w_rot=1.000000
