# This file was generated by kuka_calib
# Transform from the base camera frame to the camera link
# Position
export cam_2_x_pos=0.000000
export cam_2_y_pos=0.000000
export cam_2_z_pos=0.000000
#Rotation
export cam_2_x_rot=0.000000
export cam_2_y_rot=0.000000
export cam_2_z_rot=0.000000
export cam_2_w_rot=1.000000
